---
sudo: required
group: bluezone
language: generic

# Environment variables (setup endpoint to IBM github)
env:
  global:
  - OCTOKIT_API_ENDPOINT="https://github.ibm.com/api/v3/"

services:
  - docker

before_install:
  - source travis-env.sh
  
script:
  - make release-chart
