global:
  ## Reference to one or more secrets to be used when pulling images
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  imagePullSecrets: []
  # - name: "image-pull-secret"

  # Optional priority class to be used for the cert-manager pods
  priorityClassName: ""
  rbac:
    create: true

  leaderElection:
    # Override the namespace used to store the ConfigMap for leader election
    namespace: ""

replicaCount: 1

nodeSelector:
  master: "true"

tolerations:
- effect: NoSchedule
  key: dedicated
  operator: Exists
- key: CriticalAddonsOnly
  operator: Exists

strategy: {}
  # type: RollingUpdate
  # rollingUpdate:
  #   maxSurge: 0
  #   maxUnavailable: 1

podAnnotations: {}

# Optional additional arguments for cainjector
extraArgs: []

resources: {}
  # requests:
  #   cpu: 10m
  #   memory: 32Mi

image:
  repository: hyc-cloud-private-scratch-docker-local.artifactory.swg-devops.com/crystal/icp-cert-manager-cainjector-amd64
  tag: 0.7.0-b3be2387
  pullPolicy: IfNotPresent
