apiVersion: scheduling.k8s.io/v1alpha1
kind: PriorityClass
metadata:
  name: system-cluster-critical
value: 2000000000
globalDefault: false
description: "Used for system critical pods that must run in the cluster, but can be moved to another node if necessary."