global:
  ## Reference to one or more secrets to be used when pulling images
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  imagePullSecrets: []
  # - name: "image-pull-secret"

  # Optional priority class to be used for the cert-manager pods
  priorityClassName: ""
  rbac:
    create: true

replicaCount: 1

strategy: {}
  # type: RollingUpdate
  # rollingUpdate:
  #   maxSurge: 0
  #   maxUnavailable: 1

podAnnotations: {}

# Optional additional arguments for webhook
extraArgs: []

resources: {}
  # requests:
  #   cpu: 10m
  #   memory: 32Mi

image:
  repository: ibmcom/icp-cert-manager-webhook
  tag: 0.7.0.1
  pullPolicy: IfNotPresent

nodeSelector:
  master: "true"

tolerations:
- effect: NoSchedule
  key: dedicated
  operator: Exists
- key: CriticalAddonsOnly
  operator: Exists
# if true, the apiserver's cabundle will be automatically injected into the
# webhook's ValidatingWebhookConfiguration resource by the CA injector.
# in future this will default to false, as the apiserver can use the loopback
# configuration caBundle to talk to itself in kubernetes 1.11+
# see https://github.com/kubernetes/kubernetes/pull/62649
injectAPIServerCA: true

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

podDnsPolicy: "ClusterFirstWithHostNet"
