apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-webhook-ca
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "cert-manager.name" . }}
    chart: {{ template "cert-manager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: kubernetes.io/tls
data:
  tls.key: ''
  tls.crt: ''
