apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentials.secretName }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "webhook.name" . }}
    chart: {{ include "webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  admin_username: {{ .Values.credentials.defaultAdminUser | toString | b64enc }}
  oidc_url: {{ .Values.credentials.oidcUrl | toString | b64enc }}
