apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentials.secretName }}
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  admin_username: {{ .Values.credentials.defaultAdminUser | toString | b64enc }}
  oidc_url: {{ .Values.credentials.oidcUrl | toString | b64enc }}
