apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentials.secretName }}
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  admin_username: {{ .Values.credentials.defaultAdminUser | toString | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.apiKey.secretName }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    ibm.com/iam-service.api-key: {{ .Values.apiKey.name }}
    ibm.com/iam-service.id: {{ .Values.apiKey.serviceId }}
    ibm.com/iam-service.name: {{ .Values.apiKey.serviceName }}
type: Opaque
data:
