apiVersion: v1
kind: Secret
metadata:
  name: default-credentials
  namespace: cert-manager
type: Opaque
data:
  admin_username: {{ .Values.config.default_admin_user | toString | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-api-key
  namespace: cert-manager
  annotations:
    ibm.com/iam-service.api-key: webhook-api-key
    ibm.com/iam-service.id: cm-webhook-service-id
    ibm.com/iam-service.name: cm-webhook-service-name
type: Opaque
data:
