# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: {{ include "webhook.rootCAIssuer" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "webhook.name" . }}
    app.kubernetes.io/instance: {{ include "webhook.fullname" . }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/component: {{ .Values.component }}
    app.kubernets.io/part-of: {{ include "webhook.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ca:
    secretName: {{ include "webhook.rootCACertificate" . }}
