{{- if .Values.global.rbac.create -}}
# apiserver gets the ability to read authentication. This allows it to
# read the specific configmap that has the requestheader-* entries to
# api agg
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "webhook.fullname" . }}-webhook-authentication-reader
  namespace: kube-system
  labels:
    app.kubernetes.io/name: {{ include "webhook.name" . }}
    app.kubernetes.io/instance: {{ include "webhook.fullname" . }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/component: {{ .Values.component }}
    app.kubernets.io/part-of: {{ include "webhook.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: {{ include "webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
