# Finally, generate a serving certificate for the webhook to use
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ include "webhook.servingCertificate" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "webhook.name" . }}
    chart: {{ include "webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  secretName: {{ include "webhook.servingCertificate" . }}
  duration: 8760h # 1y
  issuerRef:
    name: {{ include "webhook.rootCAIssuer" . }}
  dnsNames:
  - {{ include "webhook.fullname" . }}
  - {{ include "webhook.fullname" . }}.{{ .Release.Namespace }}
  - {{ include "webhook.fullname" . }}.{{ .Release.Namespace }}.svc
