global:
  pullSecret: ""
  isOpenshift: false
  priorityClassName: ""
  rbac:
    create: true
  logLevel: 2
  leaderElection:
    namespace: ""
  replicaCount: 1
  strategy: {}
  tolerations: {}
imageTagPostfix: ""
image:
  name: cert-manager-controller
  repository: quay.io/open-cluster-management
  tag: 3.5.0
  pullPolicy: IfNotPresent
solver:
  name: cert-manager-acmesolver
  repository: quay.io/open-cluster-management
  tag: 0.10.1
clusterResourceNamespace: kube-system
serviceAccount:
  create: false
  name: default
extraArgs: null
extraEnv:
- name: OWNED_NAMESPACE
  value: ""
resources:
  requests:
    memory: 150Mi
    cpu: 100m
  limits:
    memory: 300Mi
    cpu: 300m
securityContext:
  pod:
    enabled: false
    fsGroup: 1001
    runAsNonRoot: true
  container:
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    privileged: false
podAnnotations: {}
podLabels: {}
podDnsPolicy: ClusterFirstWithHostNet
ingressShim: {}
prometheus:
  enabled: false
  servicemonitor:
    enabled: false
    prometheusInstance: default
    targetPort: 9402
    path: /metrics
    interval: 60s
    scrapeTimeout: 30s
    labels: {}
affinity: {}
podRestart:
  enabled: true
cert-manager-crd:
  enabled: true
cert-manager-webhook:
  enabled: true
  args:
    verbosity: 1
  extraArgs: []
  resources:
    limits:
      memory: 300Mi
      cpu: 200m
    requests:
      memory: 150Mi
      cpu: 100m
  imageTagPostfix: ""
  image:
    name: cert-manager-webhook
    repository: quay.io/open-cluster-management
    tag: 0.10.1
    pullPolicy: IfNotPresent
  injectAPIServerCA: true
  podAnnotations: {}
  serviceAccount:
    create: false
    name: default
  watcher:
    optIn: true
    configmap:
      name: extension-apiserver-authentication
      namespace: kube-system
  pkiNamespace: kube-system
cainjector:
  enabled: true
  imageTagPostfix: ""
  image:
    name: cert-manager-cainjector
    repository: quay.io/open-cluster-management
    tag: 0.10.1
    pullPolicy: IfNotPresent
  resources: {}
  extraArgs: []
  podAnnotations: {}
  podDnsPolicy: ClusterFirstWithHostNet
  serviceAccount:
    create: false
    name: default
