imagePullSecret: ""
global:
  isOpenshift: false
  priorityClassName: ""
  rbac:
    create: true
  logLevel: 2
  leaderElection:
    namespace: ""
replicaCount: 1
strategy: {}
imageTagPostfix: ""
image:
  name: cert-manager-controller
  repository: quay.io/open-cluster-management
  tag: 3.5.0
  pullPolicy: IfNotPresent
solver:
  name: icp-cert-manager-acmesolver
  repository: quay.io/open-cluster-management
  tag: 0.10.1
clusterResourceNamespace: kube-system
serviceAccount:
  create: false
  name: default
extraArgs:
- --enable-certificate-owner-ref=true
extraEnv: []
resources:
  requests:
    memory: 150Mi
    cpu: 100m
  limits:
    memory: 300Mi
    cpu: 300m
securityContext:
  pod:
    enabled: false
    fsGroup: 1001
    runAsNonRoot: true
  container:
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    privileged: false
podAnnotations: {}
podLabels: {}
podDnsPolicy: ClusterFirstWithHostNet
ingressShim: {}
prometheus:
  enabled: false
  servicemonitor:
    enabled: false
    prometheusInstance: default
    targetPort: 9402
    path: /metrics
    interval: 60s
    scrapeTimeout: 30s
    labels: {}
affinity: {}
tolerations: {}
podRestart:
  enabled: true
cert-manager-crd:
  enabled: true
