global:
  __metadata:
    label: "Global Chart Settings"
    description: "Global values for cert-manager chart"
  imagePullSecrets:
    __metadata:
      label: "Image Pull Secrets"
      description: "Any secrets required to pull cert-manager images."
      type: "string"
      required: false
  priorityClassName:
    __metadata:
      label: "Priority Class Name"
      description: "Optional priority class to be used for the cert-manager pods."
      type: "string"
      required: false
  rbac:
    create:
      __metadata:
        label: "Rbac for certificate resources"
        description: "If true, create and use RBAC resources"
        type: "boolean"
        required: true
replicaCount:
  __metadata:
    label: "Replicas"
    description: "Number of cert-manager replicas"
    type: "number"
    required: true
strategy:
  __metadata:
    label: "Strategy"
    description: "The type of update strategy to apply to cert-manager."
    type: "string"
    required: false
image:
  __metadata:
    label: "Image"
    description: "Image to be used for cert-manager deployment"
  repository:
    __metadata:
      label: "Image Repository"
      description: "Full repository and path to Certificate Manager image."
      type: "string"
      required: true
  tag:
    __metadata:
      label: "Image Tag"
      description: "The tag identifying which Certificate Manager image to deploy."
      type: "string"
      required: true
  pullPolicy:
    __metadata:
      label: "Pull Policy"
      description: "The policy used by Kubernetes for images."
      type: "string"
      required: true
      options:
      - label: "Never"
        value: "Never"
      - label: "IfNotPresent"
        value: "IfNotPresent"
      - label: "Always"
        value: "Always"
serviceAccount:
  __metadata:
    label: "Service Account"
    description: "Creates a new service account."
  create:
    __metadata:
      label: "Create"
      description: "If true, create a new service account."
      type: "boolean"
      required: true
  name:
    __metadata:
      label: "Service Account Name"
      description: "Service account to be used. If not set and serviceAccount.create is true, a name is generated using the fullname template."
      type: "string"
      required: false
extraArgs:
  __metadata:
    label: "Additional Arguments"
    description: "Optional flags for cert-manager"
    type: "string"
    required: false
securityContext:
  __metadata:
    label: "Security Context"
    description: "The security context cert-manager uses."
  readOnlyRootFilesystem:
    __metadata:
      label: "Read Only File System"
      description: "If true, then only allows reads from the file system."
      type: "boolean"
  allowPrivilegeEscalation:
    __metadata:
      label: "Allow Privilege Escalation"
      description: "If true, allows a user within the cert-manager container to escalate their privilege to root."
      type: "boolean"    
podAnnotations:
  __metadata:
    name: "podAnnotations"
    label: "Pod Annotations"
    description: "Annotations to add to the cert-manager pod"
    immutable: false
    required: false
    type: "string"
nodeSelector:
  __metadata:
    name: "nodeSelector"
    label: "Node selector"
    description: "Node labels for pod assignment"
    type: "string"
    immutable: false
    required: false
resources:
  __metadata:
    label: "Resources"
    description: "Resource requests and limits for cpu and memory for cert-manager deployment"
  requests:
    __metadata:
      label: "Requests"
      description: "The amount of cpu/memory requested by cert-manager's deployment"
    memory:
      __metadata:
        label: "Memory request"
        description: "The amount of memory cert-manager requests"
        required: false
        type: "string"
  limits:
    __metadata:
      label: "Limits"
      description: "The amount of cpu/memory cert-manager deployment is limited to"
    memory:
      __metadata:
        label: "Memory limit"
        description: "The memory limit cert-manager has"
        required: true
        type: "string"
cainjector:
  __metadata:
    label: "CA Injector"
    description: "Cert-manager webhook's CA injector subchart."
    hidden: true
  enabled:
    __metadata:
      label: "Enabled"
      description: "If true, enables the CA injector subchart to be installed."
      type: "boolean"
      immutable: true
      hidden: true
tolerations:
  __metadata:
    label: "Tolerations"
    description: "When specified, tolerates any taint that matches the triple <key, value, effect>"
    type: "string"
    required: false
affinity:
  __metadata:
    label: "Affinity"
    description: "Pod's affinity"
    hidden: true
