# requirements.yaml
dependencies:
- name: ibm-cert-manager-crd
  version: "0.7.0"
  repository: "file://ibm-cert-manager-crd"
- name: webhook
  version: "0.7.0"
  repository: "file://webhook"
  condition: webhook.enabled
- name: cainjector
  version: "0.7.0"
  repository: "file://cainjector"
  condition: cainjector.enabled
- name: ibm-cert-policy-controller
  version: "0.0.1"
  repository: "file://icp-cert-policy-controller"
  condition: policy-controller.enabled
