# requirements.yaml
dependencies:
- name: ibm-cert-manager-crd
  version: "3.4.0"
  repository: "file://ibm-cert-manager-crd"
  alias: crd
- name: controller
  version: "3.4.1"
  repository: "file://ibm-cert-policy-controller"
  condition: policyController.enabled
  alias: controller
 
