global:
  imagePullSecrets:
    __metadata:
      label: "Image Pull Secrets"
      description: "Any secrets required to pull cert-manager images."
      type: "array"
      items:
        type: "string"
      required: false
      default: []
  priorityClassName:
    __metadata:
      label: "Priority Class Name"
      description: "Optional priority class to be used for the cert-manager pods."
      type: "string"
      required: false
      default: ""
  leaderElection:
    namespace:
      __metadata:
        label: "The namespace for ConfigMap"
        description: "Override the namespace used to store the ConfigMap for leader election"
        type: "string"
        required: false
        default: "kube-system"
  rbac:
    create:
      __metadata:
        label: "Rbac for certificate resources"
        description: "If true, create and use RBAC resources"
        type: "boolean"
        required: true
        default: true

  __metadata:
    label: "Global"
    description: "Global variables for cert-manager."
    type: ""
replicaCount:
  __metadata:
    label: "Replicas"
    description: "Number of cert-manager replicas"
    type: "number"
    required: true
    default: 1    
image:
  repository:
    __metadata:
      label: "Image Repository"
      description: "Full repository and path to Certificate Manager image."
      type: "string"
      required: true
      default: "ibmcom/icp-cert-manager-controller"
  tag:
    __metadata:
      label: "Image Tag"
      description: "The tag identifying which Certificate Manager image to deploy."
      type: "string"
      required: true
      default: "0.7.0"
  pullPolicy:
    __metadata:
      label: "Pull Policy"
      description: "The policy used by Kubernetes for images."
      type: "string"
      required: true
      default: "IfNotPresent"
      options:
      - label: "Never"
        value: "Never"
      - label: "IfNotPresent"
        value: "IfNotPresent"
      - label: "Always"
        value: "Always"
solver:
  repository:
    __metadata:
      label: "ACME Solver Repository"
      description: "Full repository and path to Certificate Manager ACME Solver image."
      type: "string"
      required: true
      default: "ibmcom/icp-cert-manager-acmesolver"
  tag:
    __metadata:
      label: "Image Tag"
      description: "The tag identifying which Certificate Manager ACME Solver image to deploy."
      type: "string"
      required: true
      default: "0.5.0"
clusterResourceNamespace:
  __metadata:
    label: "The namespace for cluster resources"
    description: "Override the namespace used to store DNS provider credentials etc. for ClusterIssuer resources"
    type: "string"
    required: false
    default: "kube-system"
serviceAccount:
  create:
    __metadata:
      label: "Service Account"
      description: "If true, create a new service account"
      type: "boolean"
      required: true
      default: true
  name:
    __metadata:
      label: "The name of service account"
      description: "Service account to be used. If not set and serviceAccount.create is true, a name is generated using the fullname template"
      type: "string"
      required: false
extraArgs:
  __metadata:
    label: "Additional arguments"
    description: "Optional flags for cert-manager"
    type: "array"
    items: 
      type: "string"
    required: false
    default: []
podAnnotations:
  __metadata:
    name: "podAnnotations"
    label: "Pod Annotations"
    description: "Annotations to add to the cert-manager pod"
    type: "string"
    immutable: "false"
    required: false
    default: {}
podLabels:
  __metadata:
    name: "podLabels"
    label: "Pod Labels"
    description: "Labels to add to the cert-manager pod"
    type: "string"
    immutable: "false"
    required: false
    default: {}
nodeSelector:
  __metadata:
    name: "nodeSelector"
    label: "Node selector"
    description: "Node labels for pod assignment"
    type: "string"
    immutable: "false"
    required: false
    default: {}
